name: testable_riverpod_sample
description: A Flutter project for testable riverpod sample.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^2.17.5
  flutter: ^3.0.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  firebase_core: ^1.19.1
  cloud_firestore: ^3.2.1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.7
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
