name: testable_riverpod_sample
description: A Flutter project for testable riverpod sample.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_riverpod: ^1.0.3
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8

flutter:
  uses-material-design: true
